global:
  scrape_interval:     1s
  evaluation_interval: 1s

  external_labels:
      monitor: 'ID Generation'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'Long ID Generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['host.docker.internal:8080']

  - job_name: 'Hibenrate UUID Generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['host.docker.internal:8081']

  - job_name: 'Java UUID Generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['host.docker.internal:8082']

  - job_name: 'NanoID Generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['host.docker.internal:8083']

