{
 "title": "Execution dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Execution Time by Job",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (rate(method_execution_time_seconds_sum{layer=\"Controller\"}[1m])) / \nsum by(job) (rate(method_execution_time_seconds_count{layer=\"Controller\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Time per Method",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(job, method) (rate(method_execution_time_seconds_sum[1m])) / \nsum by(job, method) (rate(method_execution_time_seconds_count[1m]))",
     "legendFormat": "{{job}} - {{method}}"
    }
   ]
  },
  {
   "title": "Execution Time by Layer",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(job, layer) (rate(method_execution_time_seconds_sum[1m])) / \nsum by(job, layer) (rate(method_execution_time_seconds_count[1m]))",
     "legendFormat": "{{job}} - {{layer}}"
    }
   ]
  }
 ]
}